spring.application.name=catalog-service

server.port=8081
server.shutdown=graceful
management.endpoints.web.exposure.include=*

# Enables the data to be shown
management.info.env.enabled=true
management.info.java.enabled=true
management.info.os.enabled=true
management.info.build.enabled=true
management.info.git.enabled=true

#Connect to DB service
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/catalogdb}
spring.datasource.username=${DB_USERNAME:polaris}
spring.datasource.password=${DB_PASSWORD:polaris}
spring.jpa.hibernate.ddl-auto=validate

# Flyway:
spring.flyway.enabled=true